### ISSUE TITLE
PDS_ukol1

### ISSUE THREAD

**Issue by TriceGorniak** [TriceGorniak/PythonForDataScience#1]
@vaclavcepelak je to tady :)

**Comment by vaclavcepelak** [comment]
Ahoj Beato, poradila sis s tím skvěle! Nenašel jsem tam žádnou chybu. V rámci toho, co jsme se na kurzu učili, je úkol splněn. Je tam pár věcí, na které by bylo dobrý se podívat, ale nechávám na tvých časových možnostech, jestli se tím chceš zabývat. Pokud by sis chtěla udělat bonus 3, bylo by to super, protože kategorické proměnné v regresi určitě využiješ. Nabízím pomocnou ruku, pokud bys potřebovala radu. 

Na co by bylo dobrý se podívat:

- Celkově je vidět, že jedeš podle šablony, což je pochopitelné, protože to (nejspíš) děláš podruhé v životě :). NIcméně je dobrý se učit, že je třeba u všech věcí, které děláš, mít představu o tom, co to způsobuje. A zároveň si víc číst ty výstupy a komentovat je. Například po odstranění vlivných pozorování (Cook distance) ti v modelu výrazně kleslo R2, což by si zasloužilo komentář. Zároveň by bylo dobře vědět, kolik těch vlivných pozorování jsi odstranila.

- Základní rada je si udělat co nejvíc grafů: distribuce hodnot (`sns.histplot(data["Y"], kde=True)`), distribuce reziduí (sns.histplot(result.resid, kde=True)), regresní graf predikovaných a skutečných hodnot (`sns.regplot(data, x="Predicted_Y", y="Y")`) - ten ti ukáže, že tam je pár odlehlých pozorování, která jsou extrémně vlivná. Z těch grafů většinou dokážeš odhalit, že v datech je něco nečekaného - nějaký problém, který je třeba řešit.
To je taky důvod, proč ti vyšlo R2 ve druhém případě tak nízké. Ten model prostě těch pár případů netrefil, protože k tomu potřeboval hodnoty z těch sloupců, které jsi vyřadila. Obecně tady máme málo dat s "nenormální" distribucí (to bude ostatně vidět i z těch histogramů, které bych doporučoval si udělat), takže ten model je pak hodně nestabilní a s jakoukoliv změnou všechno strašně lítá. (Myslím, že je to trochu nešťastně vybraný úkol, ale zas aspoň vidíš, že v životě nepracuješ jen s hezkými daty.)
Ten problém se ukazuje i v nenormalitě reziduí (Jarque-Beta test - bylo to v lekci 6)


Formální doporučení:

- Zkus ten notebook trochu víc učesat, aby vypadal hezky (např. přidat nadpis a nějaký kontext té úlohy, že je pro kurz Czechitas atp.), Třeba se k tomu budeš chtít jednou vrátit nebo to ukázat někomu během pohovoru ;-).
- Když vyřadíš jeden řádek dat (`data_corr = data_corr[data_corr['Cook Distance'] <= 1]`), začne ti pandas vracet varování `A value is trying to be set on a copy of a slice from a DataFrame.`. Na to dávej bacha, protože tam může vzniknout chyba. Zapisuješ tam data z jednoho datového souboru do druhého a v jednom z nich je o jeden řádek méně (`data["residuals3"]=data_corr["residuals3"]`). Takže si pak vždy zkontroluj, že ten jeden řádek má chybějící hodnotu a že se nerozhodily indexy.
- Když data měníš (odmazáváš z nich řádky), založ si raději nová data (pokud paměť dovolí) a pracuj dál s nimi. Může se stát, že budeš ta původní potřebovat a budeš pak muset spouštět celý skript znova.

Kdyby bylo něco nejasné, ptej se, jsem k dispozici. Pokud chceš, abych úkol uzavřel a nechceš už se jím dál zabývat, dej vědět a zadám to do tabulky.
Díky, V.
