### ISSUE TITLE
PDS_ukol2 @vaclavcepelak

### ISSUE THREAD

**Issue by TriceGorniak** [TriceGorniak/PythonForDataScience#2]
Odevzdávám druhý úkol. Docela v tom plavu, tak jsem si pomohla AI kvůli dovysvětlení některých věcí. Zarazilo mě hned úvodní nahrání datasetu, nedošlo mi, že první část kódu to obsahuje, hledala jsem pořád název datasetu :). Ale tak snad to nějak je, když mi vychází stejný výsledky jako na obrázku. 

Na designové úpravy jsem lenoch, ale snažila jsem se to víc popsat a zvýraznit, působí to už líp, nebo mám ještě upravit?

Bea

**Comment by vaclavcepelak** [comment]
Ahoj Beato, dobrá práce! Všechno funguje, jak má, takže úkol je splněn. Pár poznámek, které nejsou zásadní:
- chybí ti tam StandardScaler. A zároveň to není chyba, protože v tomhle případě zrovna není potřeba - věděla bys proč?
(stačí, když si odpovíš pro sebe)

- Jirka do zadání psal, ať použiješ defaultní hodnotu "ovo", ale default v aktuální verzi sklearn pro decision_function_shape je "ovr". Abys to měla pod kontrolou, doporučuju to explicitně nastavovat.

- Máš tam jednu buňku, kde chybí import. 

Díky za účast na kurzu a přeju hodně štěstí v práci s daty a i jinak!

V.
